[projects]

[projects.default]
contents = [
    "about",
    "matrix_multiplication",
    "bat_and_ball",
    "camel_case",
    "toothpaste",
    "bile",
    "recursion",
    "progress_bar",
    "pascals_triangle",
    "tree",
    "roman_numerals",
    "cheque",
    "leap_year",
    "calendar",
    "prime_numbers",
    "tic_tac_toe",
    "compound_interest",
    "mortgage",
    "overpayment",
    "logo",
    "transcription",
    "translation",
    "stem_and_leaf",
    "altruism",
    "shift",
    "caesar",
    "vigenere",
    "the_end",
]

# Full URL, required for the sitemap and robots.txt.
online_url = "https://b-lukaszuk.github.io/BS_wJ_eng/"

# Extra directories to be copied.
extra_directories = ["images"]

# Port used by serve()
port = 8004

output_filename = "BS_wJ_eng"
